name: Deploy to GitHub Pages

on:
  push:
    branches:
      - eliok/winxp

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Debug - Show current branch
      run: git branch --show-current

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Build
      run: npm run build
      env:
        CI: false

    - name: Debug - List build directory contents
      run: ls -R build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build

    - name: Debug - Show gh-pages branch content
      if: success()
      run: |
        git fetch origin gh-pages
        git checkout gh-pages
        ls -R