name: Deploy to GitHub Pages

on:
  push:
    branches:
      - eliok/winxp

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Updated to a more recent LTS version

    - name: Debug - List directory contents
      run: ls -la

    - name: Debug - Display package.json content
      run: cat package.json

    - name: Debug - Display Node and npm versions
      run: |
        node --version
        npm --version

    - name: Install dependencies
      run: |
        npm cache clean --force
        npm install --legacy-peer-deps

    - name: Build
      run: npm run build
      env:
        CI: false

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
